version: '3'
services:
  ascent-discovery:
    image: ascent/ascent-discovery
    environment:
      - SPRING_PROFILES_ACTIVE=aws-ci
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8761/health"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
        - ascentnet
    ports:
        - "8761"
  
  ascent-config:
    image: ascent/ascent-config
    ports:
    - 8760
    environment:
    - SPRING_PROFILES_ACTIVE=aws-ci
    - VAULT_ADDR=https://${VAULT_ADDR}
    - VAULT_TOKEN=${VAULT_TOKEN}
    - VAULT_HOST=${VAULT_HOST}
    - VAULT_PORT=${VAULT_PORT:-8200}
    - VAULT_SCHEME=https
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8760/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
    - ascentnet
  
networks:
  ascentnet:
    driver: overlay