version: '3.3'
services:
  
  ascent-config:
    image: ascent/ascent-config:${RELEASE_VERSION:-latest}
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-docker-demo}
      - VAULT_ADDR=${VAULT_SCHEME:-https}://${VAULT_HOST:-vault}:${VAULT_PORT:-8200}
      - VAULT_TOKEN=${VAULT_TOKEN:-vaultroot}
      - VAULT_HOST=${VAULT_HOST:-vault}
      - VAULT_PORT=${VAULT_PORT:-8200}
      - VAULT_SCHEME=${VAULT_SCHEME:-https}
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      placement:
        constraints:
          - node.role == worker
    networks:
        - ascentnet
    ports:
        - "${PORT:-8760:8760}"
  
networks:
  ascentnet:
    external:
      name: ascentnet