management:
  context-path: /actuator
server:
  port: ${config.server.port:8760}
info:  
  build:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
spring:
  cloud:
    bus:
      enabled: false
    config:
      server:
        vault:
          order: 0
          host: ${VAULT_HOST:vault}
          port: ${VAULT_PORT:8200}
          scheme: ${VAULT_SCHEME:http}          
        git:
          order: 1
          uri: https://github.com/department-of-veterans-affairs/ascent-ext-configs.git
          username: ${git.access_token}
          password:
          force-pull: true
          timeout: 10
          searchPaths: ascent*
          basedir: ${BASE_DIR:../configrepo}
security:
  basic:
    enabled: false
  user:
    name: ${ascent.security.username:admin}
    password: ${ascent.security.password:default}
endpoints:
  health:
    sensitive: false
management.health.rabbit.enabled: false
health.config.enabled: false
spring.cloud.config.server.health.enabled: false
---
spring:
  profiles: docker-demo, aws-ci, aws-stage, aws-prod
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: ${messagebroker.host:ascent-amqp}
    port: ${messagebroker.port:5672}
    username: ${messagebroker.username:guest}
    password: ${messagebroker.password:guest}