management:
  context-path: /actuator
server:
  port: ${config.server.port:8760}
info:  
  build:
    version:  "@project.version@"
    artifact: "@project.artifactId@"
    name: "@project.name@"
    description: "@project.description@"
spring:
  cloud:
    bus:
      enabled: false
    config:
      server:
        vault:
          order: 0
          host: ${VAULT_HOST:vault}
          port: ${VAULT_PORT:8200}
          scheme: ${VAULT_SCHEME:http}          
        git:
          order: 1
          uri: https://github.com/department-of-veterans-affairs/ascent-ext-configs.git
          username: ${git.access_token}
          password:
          force-pull: true
          timeout: 10
          searchPaths: ascent*,vetservices*
          basedir: ${BASE_DIR:../configrepo}
security:
  basic:
    enabled: true
  user:
    name: ${ascent.security.username:admin}
    password: ${ascent.security.password:default}
endpoints:
  health:
    sensitive: false
management.health.rabbit.enabled: false
health.config.enabled: false
spring.cloud.config.server.health.enabled: false
---
spring:
  profiles: docker-demo, aws-ci, aws-stage, aws-prod
  cloud:
    bus:
      enabled: true
  rabbitmq:
    host: ${messagebroker.host:ascent-amqp}
    port: ${messagebroker.port:5672}
    username: ${spring.rabbitmq.username:guest}
    password: ${spring.rabbitmq.password:default}

server:
  ssl:
    enabled: true
    ######### These properties are set by the run-wrapper.sh script in the ascent-base container #########
    # key-alias: @project.name@
    # key-store: /app/certs/server.jks
    # key-store-password: 
    # trust-store: /app/certs/server-truststore.jks
    # trust-store-password:
    ######################################################################################################
    client-auth: need
    
---
spring:
  profiles: aws-prod, aws-stage
# Setting ascent.cloud.config.label tells our Github monitoring code which branch to monitor
# for updates for specific profiles. When property is set, it will ignore updates on other branches.
ascent:
  cloud:
    config:
      label: master
---
spring:
  profiles: aws-ci
ascent:
  cloud:
    config:
      label: development
