version: "3.3"
services:
  ascent-config: 
    image: ascent/ascent-config
    build:
      context: ../
    ports:
     - "8760:8760"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=vaultroot
      - VAULT_HOST=vault
      - VAULT_SCHEME=http
      - BASE_DIR=/configrepo/repo
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    depends_on:
      - ascent-discovery
    volumes:
      - configrepo:/configrepo
    networks:
        - ascentnet
networks:
  ascentnet:
    driver: bridge
volumes:
  configrepo:
